services:

  telegraf:
    image: telegraf:1.37
    container_name: telegraf
    network_mode: host
    environment:
      - ZONE_ID=11
      - BUILDING_ID=16
      - PROBE_ID=7
      - PROBE_NAME=probe1
      # - INFLUXDB_URL=http://192.168.1.150:8086
      # - INFLUXDB_URL=https://192.168.1.150:8086
      # - INFLUXDB_URL=https://localhost:8086
      - INFLUXDB_URL=https://10.31.109.61:8086
      - INFLUXDB_TOKEN=f/+9bxJ2nWfPGK6INsDyuMigGiqqNPRjoC1/GBaHI3A=
      # - BACKEND_URL=http://host.docker.internal:8000
      - BACKEND_URL=http://10.31.109.61:8000
    volumes:
      - ./telegraf:/etc/telegraf/
      - ./telegraf/certs/influxdb-selfsigned.crt:/etc/telegraf/ca.pem:ro
    restart: always
  # telegraf2:
  #   image: telegraf:1.37
  #   container_name: telegraf2
  #   network_mode: host
  #   environment:
  #     - PROBE_NAME=probe2
  #   volumes:
  #     - ./telegraf:/etc/telegraf/
  #   restart: always

  # mosquitto:
  #   image: eclipse-mosquitto
  #   container_name: mosquitto
  #   ports:
  #     - 1883:1883      # Plain MQTT
  #     # - 8883:8883    # MQTTS with TLS
  #     - 9001:9001      # WebSocket
  #   volumes:
  #     - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
  #     # - ./mosquitto/certs:/mosquitto/config/certs  # Uncomment for TLS
  #     - ./mosquitto/data:/mosquitto/data
  #     - ./mosquitto/log:/mosquitto/log
  #   restart: unless-stopped
