services:

  telegraf:
    # image: telegraf:1.37
    build: .
    container_name: telegraf
    network_mode: host
    # user: root
    environment:
      - ZONE_ID=${ZONE_ID}
      - BUILDING_ID=${BUILDING_ID}
      - PROBE_ID=${PROBE_ID}
      - PROBE_NAME=${PROBE_NAME}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - BACKEND_URL=${BACKEND_URL}
      - INTERFACE_NAME=${INTERFACE_NAME}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/telegraf.d:/etc/telegraf/telegraf.d:ro
      - ./telegraf/certs/influxdb-selfsigned.crt:/etc/telegraf/ca.pem:ro
      - ./telegraf/librespeed-cli/librespeed-cli-linux-amd64:/usr/bin/librespeed-cli:ro
      - ./telegraf/librespeed-cli/servers.json:/etc/librespeed-cli/servers.json:ro
      - ./telegraf/scripts:/etc/telegraf/scripts:ro
    restart: always
    entrypoint: ["/etc/telegraf/scripts/start_up.sh"]
    command: telegraf

  # mosquitto:
  #   image: eclipse-mosquitto
  #   container_name: mosquitto
  #   ports:
  #     - 1883:1883      # Plain MQTT
  #     # - 8883:8883    # MQTTS with TLS
  #     - 9001:9001      # WebSocket
  #   volumes:
  #     - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
  #     # - ./mosquitto/certs:/mosquitto/config/certs  # Uncomment for TLS
  #     - ./mosquitto/data:/mosquitto/data
  #     - ./mosquitto/log:/mosquitto/log
  #   restart: unless-stopped
