# [[inputs.exec]]
#   commands = ["speedtest-cli --server 158.108.4.223"]
#   commands = ["iperf3 -c 158.108.4.223 -J"]
#   timeout = "30s"
#   data_format = "json" # Or "influx" if the output supports it
  # Configure to parse output for metrics
