# Query given DNS server and gives statistics
[[inputs.dns_query]]
  interval = "300s"
  collection_jitter = "10s"
  ## servers to query
  servers = ["158.108.0.2", "158.108.0.3"]

  ## Network is the network protocol name.
  # network = "udp"

  ## Domains or subdomains to query.
  # domains = ["."]
  domains = ["google.com", "example.com", "kuwin.ku.ac.th"]

  ## Query record type.
  ## Possible values: A, AAAA, CNAME, MX, NS, PTR, TXT, SOA, SPF, SRV.
  # record_type = "A"

  ## Dns server port.
  # port = 53

  ## Query timeout
  # timeout = "2s"

  ## Include the specified additional properties in the resulting metric.
  ## The following values are supported:
  ##    "first_ip" -- return IP of the first A and AAAA answer
  ##    "all_ips"  -- return IPs of all A and AAAA answers
  # include_fields = []
