[[inputs.exec]]
  # อย่ารันถี่! เดี๋ยวเน็ตหมด หรือกระทบ user ใช้งานจริง (เช่น ทุก 1-6 ชั่วโมง)
  #interval = "1h"
  interval = "2h"
  collection_jitter = "5m"

  ## 1. คำสั่งที่ใช้รัน (ใส่ Path ให้ถูกตามที่คุณวางไฟล์ไว้ใน Container)
  # commands = ["sh -c 'librespeed-cli --json 2>&1'"]
  commands = ["sh -c 'librespeed-cli --local-json /etc/librespeed-cli/servers.json --json 2>&1'"]

  ## 3. จัดการ Data Format
  data_format = "json"

  ## 4. ตั้งชื่อ Measurement ที่จะไปโผล่ใน InfluxDB
  name_suffix = "_speedtest"

  ## 5. (Technical) การจัดการ Field และ Tag
  # Telegraf จะทำการ "Flatten" JSON อัตโนมัติ
  # เช่น "server": {"name": "Tokyo"} จะกลายเป็น field ชื่อ "server_name"
  # เราควรย้าย "server_name" ไปเป็น Tag เพื่อให้ Query แบ่งตาม Server ได้ง่าย
  tag_keys = ["server_name", "server_url"]

  ## (Optional) เลือกเก็บเฉพาะค่าที่จำเป็น ถ้าไม่อยากได้ client_ip หรือ timestamp ซ้ำ
  # json_name_key = ""

  ## ตั้งเวลา (สำคัญมาก)
  # Speedtest กินเวลานาน ต้องเผื่อ Timeout ไว้เยอะๆ ไม่งั้น Telegraf จะตัดจบก่อน
  timeout = "300s"
