[[inputs.exec]]
  # เช็ค Public IP Address ของ Probe และ MAC Address ของ Interface ที่กำหนด
  # อย่ารันถี่! (เช่น ทุก 8 ชั่วโมง)
  # interval = "8h"
  interval = "180s"

  collection_jitter = "1m"

  ## 1. คำสั่งที่ใช้รัน (ใส่ Path ให้ถูกตามที่คุณวางไฟล์ไว้ใน Container)
  # commands = ["sh -c \"ip -j addr show ${INTERFACE_NAME} | jq -c .[0] | jq -c '{interface: .ifname, mac_address: .address}'\""]
  # commands = ['''sh -c 'ip -j -4 addr show eth0 | jq -c ".[0] | {interface: .ifname, mac_address: .address, ip: .addr_info[0].local}" > /tmp/test_ip.json' ''']
  commands = ['/usr/bin/bash /etc/telegraf/scripts/get_ip.sh']
  tag_keys = ["interface"]
  json_string_fields = ["ip"]
  data_format = "json"

  name_override = "exec_ip"


