# A plugin that can transmit heartbeats over HTTP
[[outputs.heartbeat]]
  ## URL of heartbeat endpoint
  #url = "http://127.0.0.1:8000/agent/heartbeat"
  #url = "http://host.docker.internal:8000/agent/heartbeat"
  url = "$BACKEND_URL/agent/heartbeat"

  ## Unique identifier to submit for the Telegraf instance (required)
  #instance_id = "agent-123"
  instance_id = "agent-$ZONE_ID/$BUILDING_ID/$PROBE_ID"

  ## Token for bearer authentication
  # token = ""

  ## Interval for sending heartbeat messages
  interval = "60s"
  flush_jitter = "5s"

  ## Information to include in the message, available options are
  ##   hostname   -- hostname of the instance running Telegraf
  ##   statistics -- number of metrics, logged errors and warnings, etc
  ##   configs    -- redacted list of configs loaded by this instance
  include = ["hostname", "statistics"]

  ## Additional HTTP headers
  [outputs.heartbeat.headers]
    User-Agent = "telegraf"
