[[outputs.http]]
  ## URL is the HTTP or HTTPS URL to send metrics to
  # url = "http://localhost:8080/metrics"
  url = "$BACKEND_URL/agent/ip"

  ## HTTP method, one of: "POST" or "PUT"
  method = "POST"
  namepass = ["exec_ip"]

  data_format = "json"
  ## Additional HTTP headers
  [outputs.http.headers]
	Content-Type = "application/json"
	User-Agent = "telegraf"

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ##
